#!/bin/bash
#
# List packages in a dirty status
#
# Depends: dctrl-tools

set -e -u

PATH=/bin:/usr/bin

declare -r   PROGNAME=${0##*/}
declare -rix DEBUG=1

function fail {
    echo "${PROGNAME}: ${1:-"Unknown error"}" >&2
    exit 1
}
trap fail ERR

dpkg-query --list \
| \
tail -n +6 \
| \
grep -v '^.i ' \
| \
cut -nb'5-' \
| \
cut -d' ' -f1 \
| \
sort

exit
